### ISSUE TITLE
InAppNotification issue

### ISSUE THREAD

**Issue by arashetm** [autopilot3/ortto-push-ios-sdk#14]
After showing the widget by calling the `showWidget()` function of `OrttoCapture`, the shown widget could not be dismissed by tapping the close button, and I got this log:
```
Unhandled web view error: ["error": null, "message": Script error., "colno": 0, "lineno": 0]
```

**Comment by HenryHK** [comment]
Hi @arashetm, the issue should be fixed on ortto side. Could you double check? I'll close the issue for now.

**Comment by arashetm** [comment]
The widget now dismisses correctly when the close button is tapped. I appreciate the prompt resolution!
